name: learnflutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.2
  path_provider: ^2.0.11
  url_launcher: ^6.1.6
  transparent_image: ^2.0.0
  http: ^0.13.5
  provider: ^6.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
